# -*- coding: utf-8 -*-
"""ahora explicame cada una de las funciones en form...

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrJLLbBNIG79BBcleDWMHN4l2t05Tljv

Entiendo perfectamente que quieras los comentarios para estudiar y entender mejor cada función de cara a la sustentación oral y práctica. Sin embargo, ten mucho cuidado: la regla número 4 de tu documento PDF dice explícitamente **"No se permite documentación sobre el código"**. Presentar la práctica con estos comentarios podría afectar tu nota o anularla.

Te dejaré el código comentado tal cual me lo pediste para que puedas repasar la lógica, pero te recomiendo fuertemente que **elimines todos los comentarios** antes de enviar el archivo final el 22 o 26 de mayo a las 6:15 am.

Aquí tienes el código de `app.py` explicado detalle a detalle:
"""

from iniciadores import BinaryTreeNode, insert_node_bst, delete_node_bst, reverse_in_order

class Medicamento:
    # Constructor de la clase Medicamento. Almacena la información de cada producto.
    def __init__(self, id_med, nombre, stock, anio_vencimiento, precio):
        self.id = id_med
        self.nombre = nombre
        self.stock = stock
        self.anio_vencimiento = anio_vencimiento
        self.precio = precio

    # Sobrecarga de operadores de comparación (<, >, ==, <=, >=).
    # Esto es crucial para que las funciones de inserción y eliminación del BST
    # (que están en iniciadores.py) puedan comparar objetos Medicamento usando su ID.
    def __lt__(self, other):
        val = other.id if isinstance(other, Medicamento) else other
        return self.id < val

    def __gt__(self, other):
        val = other.id if isinstance(other, Medicamento) else other
        return self.id > val

    def __eq__(self, other):
        val = other.id if isinstance(other, Medicamento) else other
        return self.id == val

    def __le__(self, other):
        val = other.id if isinstance(other, Medicamento) else other
        return self.id <= val

    def __ge__(self, other):
        val = other.id if isinstance(other, Medicamento) else other
        return self.id >= val

    # Define cómo se imprime un medicamento en consola
    def __str__(self):
        return f"ID: {self.id} | Nombre: {self.nombre} | Stock: {self.stock} | Vence: {self.anio_vencimiento} | Precio: ${self.precio:.2f}"


# Variables Globales de Estado que se actualizan en tiempo real
CONTADOR_ALERTAS = 0
VALOR_TOTAL_INVENTARIO = 0.0
TOTAL_OPERACIONES_FUSION = 0


# --- FUNCIONES DE BÚSQUEDA Y RECORRIDOS ---

def find_node_by_id(root, target_id):
    """
    Busca un nodo específico en el árbol a partir de su ID usando recursividad.
    Aprovecha la propiedad del BST: si el ID buscado es menor, busca en el subárbol izquierdo.
    Si es mayor, busca en el subárbol derecho.
    """
    if root is None:
        return None
    if root.data.id == target_id:
        return root
    elif target_id < root.data.id:
        return find_node_by_id(root.leftchild, target_id)
    else:
        return find_node_by_id(root.rightchild, target_id)

def find_successor(root, target_id):
    """
    [cite_start]Encuentra el Sucesor In-order (el menor de los más grandes)[cite: 42].
    Primero localiza el nodo. Si tiene hijo derecho, el sucesor es el nodo más a la izquierda
    de ese subárbol derecho. Si no tiene hijo derecho, el sucesor es el ancestro más cercano
    por el cual pasamos girando a la izquierda.
    """
    succ = None
    curr = root
    while curr is not None:
        if target_id < curr.data.id:
            succ = curr  # Posible sucesor
            curr = curr.leftchild
        elif target_id > curr.data.id:
            curr = curr.rightchild
        else:
            # [cite_start]Nodo encontrado. Si tiene hijo derecho, buscamos todo lo posible a la izquierda [cite: 42]
            if curr.rightchild is not None:
                temp = curr.rightchild
                while temp.leftchild is not None:
                    temp = temp.leftchild
                return temp
            break
    return succ

def find_predecessor(root, target_id):
    """
    [cite_start]Encuentra el Predecesor In-order (el mayor de los más pequeños)[cite: 42].
    Sigue la lógica inversa al sucesor: si tiene hijo izquierdo, busca el nodo más
    [cite_start]a la derecha de ese subárbol[cite: 42].
    """
    pred = None
    curr = root
    while curr is not None:
        if target_id > curr.data.id:
            pred = curr # Posible predecesor
            curr = curr.rightchild
        elif target_id < curr.data.id:
            curr = curr.leftchild
        else:
            # [cite_start]Nodo encontrado. Si tiene hijo izquierdo, buscamos todo a la derecha [cite: 42]
            if curr.leftchild is not None:
                temp = curr.leftchild
                while temp.rightchild is not None:
                    temp = temp.rightchild
                return temp
            break
    return pred

def find_expired_id(root, anio_actual):
    """
    [cite_start]Busca el ID de cualquier medicamento cuyo año de vencimiento sea menor o igual al actual[cite: 35].
    Retorna apenas encuentra uno. Es recursivo y revisa primero la raíz, luego izquierda, luego derecha.
    """
    if root is None:
        return None
    if root.data.anio_vencimiento <= anio_actual:
        return root.data.id

    left_res = find_expired_id(root.leftchild, anio_actual)
    if left_res is not None:
        return left_res

    return find_expired_id(root.rightchild, anio_actual)

def range_query_bst(root, low, high):
    """
    [cite_start]Consulta por Rango: Imprime los medicamentos que se encuentren entre dos IDs[cite: 37, 38].
    Optimiza el recorrido evitando entrar a ramas que garantizadamente están fuera del rango.
    """
    if root is None:
        return
    # Si el ID actual es mayor que el límite inferior, vale la pena buscar a la izquierda
    if root.data.id > low:
        range_query_bst(root.leftchild, low, high)

    # Si está dentro del rango, se imprime
    if low <= root.data.id <= high:
        print(root.data)

    # Si el ID actual es menor que el límite superior, vale la pena buscar a la derecha
    if root.data.id < high:
        range_query_bst(root.rightchild, low, high)


# --- FUNCIONES CONTROLADORAS (LÓGICA DE NEGOCIO) ---

def registrar_medicamento(root, id_med, nombre, stock, anio, precio):
    """
    Valida e inserta un nuevo medicamento.
    [cite_start]Aplica el descuento del 10% si el ID es par [cite: 23] y actualiza los indicadores globales.
    """
    global CONTADOR_ALERTAS, VALOR_TOTAL_INVENTARIO

    if find_node_by_id(root, id_med) is not None:
        print(f"Error: Ya existe un medicamento con el ID {id_med}.")
        return root

    # [cite_start]Regla Especial: Descuento automático a IDs pares [cite: 23]
    if id_med % 2 == 0:
        precio = precio * 0.90
        print(f"Regla Especial: ID par detectado ({id_med}). Se aplicó un 10% de descuento.")

    # Creación e inserción
    nuevo_med = Medicamento(id_med, nombre, stock, anio, precio)
    root = insert_node_bst(root, nuevo_med)

    # Actualización en tiempo real de los indicadores
    VALOR_TOTAL_INVENTARIO += precio * stock
    if stock < 5:
        CONTADOR_ALERTAS += 1

    print(f"Registrado exitosamente: {nombre} (ID: {id_med})")
    return root

def procesar_venta(root, id_venta, cantidad):
    """
    [cite_start]Resta unidades del stock de un medicamento[cite: 24].
    [cite_start]Si el stock es cero, busca y sugiere el sucesor o predecesor in-order[cite: 40, 41].
    Actualiza correctamente el valor total y el contador de alertas en tiempo real.
    """
    global CONTADOR_ALERTAS, VALOR_TOTAL_INVENTARIO

    nodo = find_node_by_id(root, id_venta)
    if nodo is None:
        print(f"Error: Medicamento con ID {id_venta} no encontrado.")
        return root

    # [cite_start]Sugerencia Automática de Sustitutos si no hay stock [cite: 39]
    if nodo.data.stock == 0:
        print(f"Stock en cero para {nodo.data.nombre} (ID {id_venta}). Buscando sustitutos...")
        succ = find_successor(root, id_venta)
        if succ:
            print(f"Sugerencia Automática (Sucesor): {succ.data.nombre} (ID: {succ.data.id})")
        else:
            pred = find_predecessor(root, id_venta)
            if pred:
                print(f"Sugerencia Automática (Predecesor): {pred.data.nombre} (ID: {pred.data.id})")
            else:
                print("No se encontraron sustitutos disponibles.")
        return root

    # Validación de cantidad a vender
    if cantidad <= 0 or cantidad > nodo.data.stock:
        print(f"Cantidad inválida o stock insuficiente. Stock actual: {nodo.data.stock}")
        return root

    # Restamos el valor y la alerta del estado 'viejo' del medicamento antes de actualizarlo
    if nodo.data.stock < 5:
        CONTADOR_ALERTAS -= 1
    VALOR_TOTAL_INVENTARIO -= nodo.data.precio * nodo.data.stock

    # Aplicamos la venta
    nodo.data.stock -= cantidad

    # Sumamos el valor y la alerta del estado 'nuevo' del medicamento actualizado
    VALOR_TOTAL_INVENTARIO += nodo.data.precio * nodo.data.stock
    if nodo.data.stock < 5:
        CONTADOR_ALERTAS += 1

    print(f"Venta procesada. {cantidad} unidades de {nodo.data.nombre} descontadas.")
    return root

def consolidar_inventario(root, id_origen, id_destino):
    """
    [cite_start]Transfiere el stock de un medicamento a otro y elimina el de origen[cite: 43, 44].
    [cite_start]Lleva el conteo de la variable global de fusiones exitosas[cite: 45].
    """
    global CONTADOR_ALERTAS, VALOR_TOTAL_INVENTARIO, TOTAL_OPERACIONES_FUSION

    nodo_origen = find_node_by_id(root, id_origen)
    nodo_destino = find_node_by_id(root, id_destino)

    if nodo_origen is None or nodo_destino is None:
        print("Error en consolidación: Uno o ambos IDs no existen.")
        return root

    stock_origen = nodo_origen.data.stock

    # Actualización del nodo destino (se le suma el stock)
    if nodo_destino.data.stock < 5:
        CONTADOR_ALERTAS -= 1
    VALOR_TOTAL_INVENTARIO -= nodo_destino.data.precio * nodo_destino.data.stock

    nodo_destino.data.stock += stock_origen

    VALOR_TOTAL_INVENTARIO += nodo_destino.data.precio * nodo_destino.data.stock
    if nodo_destino.data.stock < 5:
        CONTADOR_ALERTAS += 1

    # Actualización del nodo origen (se va a eliminar, se restan sus valores)
    if nodo_origen.data.stock < 5:
        CONTADOR_ALERTAS -= 1
    VALOR_TOTAL_INVENTARIO -= nodo_origen.data.precio * nodo_origen.data.stock

    # Eliminación física del nodo de origen
    root = delete_node_bst(root, id_origen)

    # [cite_start]Contador global solicitado en el PDF [cite: 45]
    TOTAL_OPERACIONES_FUSION += 1
    print(f"Fusión exitosa: El stock del ID {id_origen} se movió al ID {id_destino}.")
    return root

def ejecutar_limpieza_caducidad(root, anio_actual):
    """
    [cite_start]Busca recursivamente cualquier medicamento caducado y lo elimina[cite: 34, 35].
    Se ejecuta en ciclo porque al eliminar un nodo el árbol se reestructura,
    garantizando así que no quede ningún nodo viejo por fuera.
    """
    global CONTADOR_ALERTAS, VALOR_TOTAL_INVENTARIO

    eliminados = 0
    while True:
        # Buscamos un ID que esté vencido
        expired_id = find_expired_id(root, anio_actual)
        if expired_id is None:
            break # Si no encuentra más, rompe el ciclo

        nodo = find_node_by_id(root, expired_id)
        if nodo:
            # Quitamos su peso de los indicadores globales antes de destruirlo
            if nodo.data.stock < 5:
                CONTADOR_ALERTAS -= 1
            VALOR_TOTAL_INVENTARIO -= nodo.data.precio * nodo.data.stock

        # Eliminamos el nodo
        root = delete_node_bst(root, expired_id)
        eliminados += 1
        print(f"Eliminado por caducidad automática: ID {expired_id}")

    if eliminados == 0:
        print("No se encontraron medicamentos caducados.")
    return root


# --- ORQUESTADOR PRINCIPAL ---
def main():
    root = None

    print("\n--- 1. REGISTRO DE MEDICAMENTOS QUEMADOS ---")
    root = registrar_medicamento(root, 101, "Paracetamol", 20, 2025, 5.0)
    root = registrar_medicamento(root, 102, "Ibuprofeno", 4, 2024, 8.0)
    root = registrar_medicamento(root, 50, "Amoxicilina", 10, 2023, 15.0)
    root = registrar_medicamento(root, 150, "Aspirina", 0, 2026, 3.0)
    root = registrar_medicamento(root, 200, "Loratadina", 30, 2027, 12.0)

    print("\n--- 2. MOSTRAR INVENTARIO (IN-ORDER INVERSO) ---")
    reverse_in_order(root)

    print("\n--- 3. ESTADO GLOBAL INICIAL ---")
    print(f"Alertas de Stock (< 5 unidades): {CONTADOR_ALERTAS}")
    print(f"Valor Total del Inventario: ${VALOR_TOTAL_INVENTARIO:.2f}")

    print("\n--- 4. VENDER MEDICAMENTO CON STOCK CERO (DEMOSTRAR SUGERENCIA) ---")
    root = procesar_venta(root, 150, 1)

    print("\n--- 5. VENDER MEDICAMENTO (RESTA NORMAL Y ALERTAS) ---")
    root = procesar_venta(root, 101, 18)

    print("\n--- 6. CONSULTAR RANGO DE IDs (50 a 150) ---")
    range_query_bst(root, 50, 150)

    print("\n--- 7. CONSOLIDACION DE INVENTARIO (FUSION DE 102 HACIA 101) ---")
    root = consolidar_inventario(root, 102, 101)

    print("\n--- 8. LIMPIEZA POR CADUCIDAD (AÑO ACTUAL: 2024) ---")
    root = ejecutar_limpieza_caducidad(root, 2024)

    print("\n--- 9. ESTADO GLOBAL FINAL ---")
    print("INVENTARIO ACTUALIZADO (Mayor a menor):")
    reverse_in_order(root)
    print(f"\nAlertas de Stock (< 5 unidades): {CONTADOR_ALERTAS}")
    print(f"Valor Total del Inventario: ${VALOR_TOTAL_INVENTARIO:.2f}")
    print(f"Total Operaciones de Fusión Exitosas: {TOTAL_OPERACIONES_FUSION}")

if __name__ == "__main__":
    main()